name: CI tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: "latest"
          token: ${{ github.token }}
      - name: Run Biome
        run: biome ci ./src
